x-relay-common: &relay-common
  SESSION_REDIS_URI: redis://redis/0
  SQLALCHEMY_DATABASE_URI: mysql+mysqldb://db:db@mariadb/relaymd?charset=utf8mb4
  GITHUB_CLIENT_ID:
  GITHUB_CLIENT_SECRET:
  MINIO_ENDPOINT: minio
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio-minio-minio

services:

  redis:
    image: redis

  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    command: "server /export --console-address :8080 --address :8081"
    ports:
      - "8080:8080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-minio-minio
      # MINIO_SERVER_URL: http://localhost:{{ env "NOMAD_PORT_minio" }}

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: relaymd
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  api:
    build: .
    environment:
      <<: *relay-common
    command: api
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - minio
      - mariadb

  web:
    build: .
    environment:
      <<: *relay-common
    command: web
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - minio
      - mariadb
