# -*- coding: utf-8 -*-
"""additional-fields-for-product

Revision ID: 0e70596d645d
Revises: 2f2a72fc3240
Create Date: 2023-12-14 10:22:07.257446

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e70596d645d"
down_revision = "2f2a72fc3240"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_product",
        sa.Column("description", sa.String(length=64), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("billing_product", "description")
    # ### end Alembic commands ###
