# -*- coding: utf-8 -*-
"""add team headline

Revision ID: 250431153a25
Revises: 9fc631b0e606
Create Date: 2023-12-21 12:29:00.547580

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "250431153a25"
down_revision = "9fc631b0e606"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("headline", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "headline")
    # ### end Alembic commands ###
