"""remove-deprecated-columns-in-invoice

Revision ID: 2947cd9d37a5
Revises: 3376a358e58f
Create Date: 2024-01-30 21:47:31.421967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2947cd9d37a5'
down_revision = '3376a358e58f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_invoice', 'payment_provider_reference')
    op.drop_column('billing_invoice', 'payment_failure_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoice', sa.Column('payment_failure_reason', mysql.TEXT(), nullable=True))
    op.add_column('billing_invoice', sa.Column('payment_provider_reference', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
