# -*- coding: utf-8 -*-
"""seats-for-teams

Revision ID: 2de90edf287a
Revises: 9a233ea067ef
Create Date: 2023-12-22 21:10:58.890808

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2de90edf287a"
down_revision = "9a233ea067ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("seats", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "seats")
    # ### end Alembic commands ###
