# -*- coding: utf-8 -*-
"""move-user-id-to-invoice

Revision ID: 2f2a72fc3240
Revises: f91aa0e21c8c
Create Date: 2023-12-14 09:57:05.125781

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f2a72fc3240"
down_revision = "f91aa0e21c8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("landing_emails")
    op.add_column("billing_invoice", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.add_column(
        "billing_invoice",
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING", "COMPLETED", "CANCELED", "EXPIRED", name="invoicestatus"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "billing_invoice", sa.Column("payment_failure_reason", sa.Text(), nullable=True)
    )
    op.create_foreign_key(None, "billing_invoice", "user", ["user_id"], ["id"])
    op.drop_constraint("billing_person_ibfk_1", "billing_person", type_="foreignkey")
    op.drop_column("billing_person", "user_id")
    op.drop_column("billing_person", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_person",
        sa.Column("country", mysql.VARCHAR(length=128), nullable=False),
    )
    op.add_column(
        "billing_person", sa.Column("user_id", mysql.CHAR(length=32), nullable=False)
    )
    op.create_foreign_key(
        "billing_person_ibfk_1", "billing_person", "user", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "billing_invoice", type_="foreignkey")
    op.drop_column("billing_invoice", "payment_failure_reason")
    op.drop_column("billing_invoice", "payment_status")
    op.drop_column("billing_invoice", "user_id")
    op.create_table(
        "landing_emails",
        sa.Column("id", mysql.CHAR(length=32), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("confirm_date", mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
