# -*- coding: utf-8 -*-
"""document-store-checksum-and-filesize

Revision ID: 3376a358e58f
Revises: 483c32cfbc45
Create Date: 2024-01-22 20:53:59.648547

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3376a358e58f"
down_revision = "483c32cfbc45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("filesize", sa.BigInteger(), nullable=True))
    op.add_column(
        "document", sa.Column("checksum_sha256", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "checksum_sha256")
    op.drop_column("document", "filesize")
    # ### end Alembic commands ###
