# -*- coding: utf-8 -*-
"""allow sharing with users

Revision ID: 337d47cd3477
Revises: 6004d8849c1e
Create Date: 2023-11-30 17:15:12.667608

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "337d47cd3477"
down_revision = "6004d8849c1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_user")
    # ### end Alembic commands ###
