# -*- coding: utf-8 -*-
"""allow-disable-subscription

Revision ID: 3911c02d6c45
Revises: 88a7f795d5d8
Create Date: 2023-12-22 13:41:28.600518

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3911c02d6c45"
down_revision = "88a7f795d5d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_subscription", sa.Column("active", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("billing_subscription", "active")
    # ### end Alembic commands ###
