# -*- coding: utf-8 -*-
"""favorit-flag-for-teams

Revision ID: 483c32cfbc45
Revises: 2de90edf287a
Create Date: 2023-12-29 21:42:04.939736

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "483c32cfbc45"
down_revision = "2de90edf287a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("favorit", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "favorit")
    # ### end Alembic commands ###
