# -*- coding: utf-8 -*-
"""document access

Revision ID: 6004d8849c1e
Revises: 8bfccb77b828
Create Date: 2023-11-30 16:09:36.977337

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6004d8849c1e"
down_revision = "8bfccb77b828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_access",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("access_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_access")
    # ### end Alembic commands ###
