# -*- coding: utf-8 -*-
"""remove-location-add-profile-pic

Revision ID: 82fe12ff1726
Revises: c7a9b2109b99
Create Date: 2023-12-09 21:42:14.499227

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "82fe12ff1726"
down_revision = "c7a9b2109b99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("profile_picture_url", sa.String(length=255), nullable=True)
    )
    op.drop_column("user", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("location", mysql.VARCHAR(length=64), nullable=True)
    )
    op.drop_column("user", "profile_picture_url")
    # ### end Alembic commands ###
