# -*- coding: utf-8 -*-
"""initial permissions

Revision ID: 8bfccb77b828
Revises: d5adcdfb4964
Create Date: 2023-11-30 15:09:53.825793

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bfccb77b828"
down_revision = "d5adcdfb4964"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("team", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.add_column("team", sa.Column("is_private", sa.Boolean(), nullable=False))
    op.add_column(
        "team", sa.Column("allow_create_topics", sa.Boolean(), nullable=False)
    )
    op.create_foreign_key(None, "team", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team", type_="foreignkey")
    op.drop_column("team", "allow_create_topics")
    op.drop_column("team", "is_private")
    op.drop_column("team", "user_id")
    op.drop_column("team", "created_at")
    # ### end Alembic commands ###
