# -*- coding: utf-8 -*-
"""remove-invoice-id

Revision ID: 942f270ba350
Revises: dd1938f2cb6f
Create Date: 2023-12-14 21:04:05.712928

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "942f270ba350"
down_revision = "dd1938f2cb6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "billing_recurring_token_ibfk_2", "billing_recurring_token", type_="foreignkey"
    )
    op.drop_column("billing_recurring_token", "invoice_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_recurring_token",
        sa.Column("invoice_id", mysql.CHAR(length=32), nullable=False),
    )
    op.create_foreign_key(
        "billing_recurring_token_ibfk_2",
        "billing_recurring_token",
        "billing_invoice",
        ["invoice_id"],
        ["id"],
    )
    # ### end Alembic commands ###
