# -*- coding: utf-8 -*-
"""add a description to team

Revision ID: aa8f047f7e49
Revises: 2947cd9d37a5
Create Date: 2024-02-19 21:09:57.683065

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa8f047f7e49"
down_revision = "2947cd9d37a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "description")
    # ### end Alembic commands ###
