# -*- coding: utf-8 -*-
"""require opt-in

Revision ID: bbaebf058a3e
Revises: 7602a266c9a4
Create Date: 2023-11-10 14:26:28.728540

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bbaebf058a3e"
down_revision = "7602a266c9a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landing_emails", sa.Column("created_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "landing_emails", sa.Column("confirm_token", sa.Uuid(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("landing_emails", "confirm_token")
    op.drop_column("landing_emails", "created_date")
    # ### end Alembic commands ###
