# -*- coding: utf-8 -*-
"""get rid-of custom mail tracking

Revision ID: d5adcdfb4964
Revises: bbaebf058a3e
Create Date: 2023-11-11 21:06:10.640760

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5adcdfb4964"
down_revision = "bbaebf058a3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("landing_emails")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "landing_emails",
        sa.Column("id", mysql.CHAR(length=32), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("confirm_date", mysql.DATETIME(), nullable=True),
        sa.Column("created_date", mysql.DATETIME(), nullable=True),
        sa.Column("confirm_token", mysql.CHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
