# -*- coding: utf-8 -*-
"""public docs and read-password

Revision ID: d7e5c92de58b
Revises: 337d47cd3477
Create Date: 2023-12-01 15:44:58.719097

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d7e5c92de58b"
down_revision = "337d47cd3477"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.add_column(
        "document", sa.Column("read_password_hash", sa.CHAR(length=32), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "read_password_hash")
    op.drop_column("document", "is_public")
    # ### end Alembic commands ###
