# -*- coding: utf-8 -*-
"""new-way-of-billing-thru-subscription

Revision ID: d8956460586b
Revises: 2947cd9d37a5
Create Date: 2024-02-08 16:02:58.229656

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d8956460586b"
down_revision = "2947cd9d37a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_subscription",
        sa.Column("period_starts_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "billing_subscription",
        sa.Column("period_ends_at", sa.DateTime(), nullable=False),
    )
    op.drop_column("team", "paid_until")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("paid_until", sa.DATE(), nullable=True))
    op.drop_column("billing_subscription", "period_ends_at")
    op.drop_column("billing_subscription", "period_starts_at")
    # ### end Alembic commands ###
