# -*- coding: utf-8 -*-
"""billing-support

Revision ID: dd1938f2cb6f
Revises: 82fe12ff1726
Create Date: 2023-12-14 12:32:31.355229

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dd1938f2cb6f"
down_revision = "82fe12ff1726"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_payment_plan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("days_between_payments", sa.Integer(), nullable=False),
        sa.Column("expiry", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_person",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("address_line1", sa.String(length=128), nullable=False),
        sa.Column("address_line2", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("zip", sa.String(length=128), nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=False),
        sa.Column("phone_country_code", sa.String(length=6), nullable=False),
        sa.Column("phone_number", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_invoice",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING", "COMPLETED", "CANCELED", "EXPIRED", name="invoicestatus"
            ),
            nullable=False,
        ),
        sa.Column("payment_failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "payment_provider", sa.Enum("ADYEN", name="paymentprovider"), nullable=False
        ),
        sa.Column("payment_provider_reference", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["billing_person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["billing_payment_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_invoice_products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["billing_invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_recurring_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("originalReference", sa.String(length=128), nullable=False),
        sa.Column("recurringDetailReference", sa.String(length=128), nullable=False),
        sa.Column("pspReference", sa.String(length=128), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["billing_invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("billing_recurring_token")
    op.drop_table("billing_invoice_products")
    op.drop_table("billing_invoice")
    op.drop_table("billing_product")
    op.drop_table("billing_person")
    op.drop_table("billing_payment_plan")
    # ### end Alembic commands ###
