# -*- coding: utf-8 -*-
"""simplify-billing

Revision ID: df3e09b22914
Revises: 942f270ba350
Create Date: 2023-12-15 10:48:44.810754

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "df3e09b22914"
down_revision = "942f270ba350"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("billing_invoice_products")
    op.drop_table("billing_payment_plan")
    op.add_column("billing_invoice", sa.Column("paid_at", sa.DateTime(), nullable=True))
    op.drop_constraint("billing_invoice_ibfk_3", "billing_invoice", type_="foreignkey")
    op.drop_column("billing_invoice", "payment_id")
    op.add_column("billing_product", sa.Column("invoice_id", sa.Uuid(), nullable=False))
    op.add_column("billing_product", sa.Column("team_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "billing_product", "billing_invoice", ["invoice_id"], ["id"]
    )
    op.create_foreign_key(None, "billing_product", "team", ["team_id"], ["id"])
    op.add_column("team", sa.Column("paid_until", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "paid_until")
    op.drop_constraint(None, "billing_product", type_="foreignkey")
    op.drop_constraint(None, "billing_product", type_="foreignkey")
    op.drop_column("billing_product", "team_id")
    op.drop_column("billing_product", "invoice_id")
    op.add_column(
        "billing_invoice",
        sa.Column("payment_id", mysql.CHAR(length=32), nullable=False),
    )
    op.create_foreign_key(
        "billing_invoice_ibfk_3",
        "billing_invoice",
        "billing_payment_plan",
        ["payment_id"],
        ["id"],
    )
    op.drop_column("billing_invoice", "paid_at")
    op.create_table(
        "billing_payment_plan",
        sa.Column("id", mysql.CHAR(length=32), nullable=False),
        sa.Column(
            "days_between_payments",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("expiry", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "billing_invoice_products",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("invoice_id", mysql.CHAR(length=32), nullable=False),
        sa.Column("product_id", mysql.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["billing_invoice.id"],
            name="billing_invoice_products_ibfk_1",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_product.id"],
            name="billing_invoice_products_ibfk_2",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
