# -*- coding: utf-8 -*-
"""subscription-billing-support

Revision ID: f91aa0e21c8c
Revises: 21d56aead7cb
Create Date: 2023-12-13 14:30:14.023489

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f91aa0e21c8c"
down_revision = "21d56aead7cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_recurring_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("originalReference", sa.String(length=128), nullable=False),
        sa.Column("recurringDetailReference", sa.String(length=128), nullable=False),
        sa.Column("pspReference", sa.String(length=128), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["billing_invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "billing_invoice",
        sa.Column(
            "payment_provider", sa.Enum("ADYEN", name="paymentprovider"), nullable=False
        ),
    )
    op.add_column(
        "billing_invoice",
        sa.Column("payment_provider_reference", sa.String(length=256), nullable=True),
    )
    op.add_column("billing_person", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "billing_person", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "billing_person", type_="foreignkey")
    op.drop_column("billing_person", "user_id")
    op.drop_column("billing_invoice", "payment_provider_reference")
    op.drop_column("billing_invoice", "payment_provider")
    op.drop_table("billing_recurring_token")
    # ### end Alembic commands ###
