---
name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
jobs:

  build:
    name: Build and Push docker container
    runs-on: ubuntu-latest

    # Required to write to ghcr.io
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.version }}
          build-args: |
            VCS_REF=${{ github.sha }}
