name: Test, build and deploy for Test

on:
  push:
    branches:
      - develop

jobs:

  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    needs: test
    with:
      version: "${{ github.ref_name }}.${{ github.run_number }}"
      registry: ghcr.io
      image: relay-md/relay.md
